//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2019 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <windows.h>

// ------------------------ Structures ------------------------

struct _EVENT_DATA_DESCRIPTOR {
    int64_t e0;
    int32_t e1;
    int32_t e2;
};

struct _EVENT_DESCRIPTOR {
    int16_t e0;
    char e1;
    char e2;
    char e3;
    char e4;
    int16_t e5;
    int64_t e6;
};

struct _EVENT_FILTER_DESCRIPTOR {
    int64_t e0;
    int32_t e1;
    int32_t e2;
};

struct _EXCEPTION_POINTERS {
    struct _EXCEPTION_RECORD * e0;
    struct _CONTEXT * e1;
};

struct _EXCEPTION_RECORD {
    int32_t e0;
    int32_t e1;
    struct _EXCEPTION_RECORD * e2;
    int32_t * e3;
    int32_t e4;
    int32_t e5[1];
};

struct _FILETIME {
    int32_t e0;
    int32_t e1;
};

struct _LARGE_INTEGER {
    int64_t e0;
};

struct _M128A {
    int64_t e0;
    int64_t e1;
};

struct _CONTEXT {
    int64_t e0;
    int64_t e1;
    int64_t e2;
    int64_t e3;
    int64_t e4;
    int64_t e5;
    int32_t e6;
    int32_t e7;
    int16_t e8;
    int16_t e9;
    int16_t e10;
    int16_t e11;
    int16_t e12;
    int16_t e13;
    int32_t e14;
    int64_t e15;
    int64_t e16;
    int64_t e17;
    int64_t e18;
    int64_t e19;
    int64_t e20;
    int64_t e21;
    int64_t e22;
    int64_t e23;
    int64_t e24;
    int64_t e25;
    int64_t e26;
    int64_t e27;
    int64_t e28;
    int64_t e29;
    int64_t e30;
    int64_t e31;
    int64_t e32;
    int64_t e33;
    int64_t e34;
    int64_t e35;
    int64_t e36;
    int64_t e37;
    int32_t e38;
    struct _M128A e39[26];
    int64_t e40;
    int64_t e41;
    int64_t e42;
    int64_t e43;
    int64_t e44;
    int64_t e45;
};

struct _STARTUPINFOW {
    int32_t e0;
    int16_t * e1;
    int16_t * e2;
    int16_t * e3;
    int32_t e4;
    int32_t e5;
    int32_t e6;
    int32_t e7;
    int32_t e8;
    int32_t e9;
    int32_t e10;
    int32_t e11;
    int16_t e12;
    int16_t e13;
    char * e14;
    int32_t * e15;
    int32_t * e16;
    int32_t * e17;
};

struct _TYPEDEF_GUID {
    int32_t e0;
    int16_t e1;
    int16_t e2;
    char e3[8];
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(void);
int32_t function_40119c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t result, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t result2, int32_t a15);
int32_t function_40148b(void);
int32_t function_401512(void);
int32_t function_401513(void);
int32_t function_401680(int32_t a1);
int32_t function_401799(void);
int32_t function_401820(void);
int32_t function_401890(void);
int32_t function_4018c3(void);
int32_t function_401a94(int32_t a1, uint32_t a2);
int32_t function_401ac5(void);
int32_t function_401b42(int32_t a1);
int32_t (*function_401b90(int32_t (*lpTopLevelExceptionFilter)(struct _EXCEPTION_POINTERS *)))(struct _EXCEPTION_POINTERS *);
int32_t function_401b9e(int32_t xcptnum, int32_t * pxcptinfoptrs);
int32_t function_401ba4(int32_t a1);
int32_t function_401c0e(int32_t result);
void function_401c44(int32_t rterrnum);
int32_t function_401c50(void);
int32_t function_401c60(int32_t a1, uint32_t a2);
int32_t function_401cb0(int32_t a1);
int32_t function_401d70(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t * a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11);
int32_t function_401da5(void);
void function_401db8(void (**First)(), void (**Last)());
int32_t function_401dc0(int32_t a1, int32_t a2, int32_t a3);
int32_t function_401e05(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t function_401e22(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_401e50(void);
int32_t function_401e53(void);

// ------------------------ Functions -------------------------

// Address range: 0x40119c - 0x40120b
int32_t function_40119c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t result, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t result2, int32_t a15) {
    struct _EXCEPTION_POINTERS * v1 = (struct _EXCEPTION_POINTERS *)0x402038;
    int32_t v2 = 0;
    int32_t v3 = 0;
    int32_t v4 = 0;
    int32_t v5 = 0;
    int16_t * v6 = (int16_t *)0x694d0029;
    int32_t v7 = 0;
    int32_t v8 = 0;
    int32_t v9 = 0;
    int32_t v10 = 0;
    int64_t * v11 = NULL;
    int32_t v12 = 0;
    int32_t v13 = 0;
    int32_t v14 = 0;
    int32_t v15 = -0x44bf19b2;
    int32_t v16 = 0x44bf19b1;
    int32_t v17 = 1;
    int32_t v18 = 0;
    int32_t v19 = 0;
    int32_t v20 = 0;
    int32_t v21 = 0;
    int32_t v22 = 0;
    int32_t v23 = 0;
    int32_t v24 = 0;
    int32_t v25 = 0;
    int32_t v26 = 0;
    int32_t v27 = 0;
    int32_t v28 = 0;
    int32_t v29 = 0;
    int32_t v30 = 0;
    int32_t v31 = 0;
    int32_t v32 = 0;
    int32_t v33 = 0;
    int32_t v34 = 0;
    int32_t v35 = 0;
    int32_t v36 = 0;
    int32_t v37 = 0;
    int32_t v38 = 0;
    int32_t v39 = 0;
    int32_t v40 = 0;
    int32_t v41 = 0;
    int32_t v42 = 0;
    int16_t *** v43 = NULL;
    int16_t *** v44 = NULL;
    int32_t v45 = 0;
    int32_t v46 = 0;
    int32_t v47 = 0;
    int32_t v48 = 0;
    int32_t v49 = 0;
    int32_t v50 = 0;
    int32_t v51 = 0;
    int32_t v52 = 0;
    int32_t v53 = 0;
    int32_t v54 = 0;
    int32_t v55 = 0;
    int32_t v56 = 0;
    int32_t v57;
    // 0x40119c
    int32_t v58; // ebx
    char * v59 = (char *)(v58 + 97); // 0x4011a6
    unsigned char v60 = *v59; // 0x4011a6
    unsigned char v61; // 0x4011a4
    unsigned char v62 = v60 - v61; // 0x4011a6
    *v59 = v62;
    int32_t v63; // edx
    __asm_insb((int16_t)v63);
    int32_t v64; // esi
    int16_t v65; // 0x4011aa
    __asm_arpl(v65, (int16_t)v64);
    if (v62 == 0) {
        // 0x401218
        return result;
    }
    // 0x4011b0
    if (v62 < v60) {
        char * v66 = (char *)result; // 0x401209
        *v66 = *v66 + (char)result;
        return result;
    }
    // 0x4011b2
    __asm_insb((int16_t)a5);
    int16_t v67; // 0x4011bd
    __asm_arpl(v67, (int16_t)a2);
    char v68; // 0x4011b9
    if ((v68 & (char)result) == 0 || false) {
        // 0x401218
        return result2;
    }
    // 0x4011c9
    char v69; // 0x4011cd
    return (int32_t)(v69 + (__readfsbyte(result2) & (char)result2)) | result2 & -256;
}

// Address range: 0x40148b - 0x40150b
int32_t function_40148b(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x40148b
    int32_t v58; // ebx
    char * v59 = (char *)(v58 - 0x1374aa01); // 0x40148f
    int32_t v60; // ecx
    *v59 = (char)v60 + *v59;
    int32_t result; // 0x401508
    int32_t v61; // 0x401495
    if (v61 == 0) {
        result = 0;
        return result;
    } else {
        // 0x40149f
        int32_t v62; // 0x40149f
        if (v62 == 0) {
            // 0x4014dd
            goto lab_0x4014e0;
        } else {
            // 0x4014b0
            if (v62 != 1) {
                // 0x4014dd
                goto lab_0x4014e0;
            } else {
                uint32_t v63; // 0x4014a8
                if ((char)v63 != 0) {
                    // branch -> 0x4014c4
                }
                // 0x4014c4
                goto lab_0x4014e0;
            }
        }
    }
    // 0x401504
    return result;
  lab_0x4014e0:;
    // 0x4014e0
    int32_t v64; // 0x4014e0
    if (v64 != 0) {
        // 0x4014e7
        result = function_401e50();
    } else {
        result = v61;
    }
    return result;
}

// Address range: 0x401512 - 0x401513
int32_t function_401512(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401512
    int32_t result;
    return result;
}

// Address range: 0x401513 - 0x401671
int32_t function_401513(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int32_t v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int32_t v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int16_t *** v34;
    int16_t *** v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int32_t v43;
    int32_t v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int64_t * v48;
    int64_t * v49 = (int64_t *)&v48; // bp-104
    int32_t v50; // 0x40153b
    struct _TYPEDEF_GUID * v51 = (struct _TYPEDEF_GUID *)&v50; // bp-116
    int32_t v52 = 0; // esi
    int32_t v53 = 0;
    int32_t v54 = 0;
    int32_t v55;
    if (EventRegister(v51, (void (*)(struct _TYPEDEF_GUID *, int32_t, char, int64_t, int64_t, struct _EVENT_FILTER_DESCRIPTOR *, int32_t *))0x401490, &v55, v49) == 0) {
        int32_t v56 = *(int32_t *)&v48; // 0x40157514
        int16_t * v57;
        int32_t v58;
        EventSetInformation((int64_t)v56, v58, (int32_t *)2, (int32_t)&v57);
    }
    // 0x401581
    int32_t v59;
    if (v55 >= 6) {
        // 0x401591
        int32_t v60;
        if ((v52 || v60 & 0x20000) != 0) {
            // 0x4015a8
            int32_t v61;
            if (v52 == v61) {
                int32_t v62;
                if ((v62 & 0x20000) == v62) {
                    // 0x4015c6
                    uint16_t v63; // 0x4015e4
                    EventWriteTransfer(0xb000011, (struct _EVENT_DESCRIPTOR *)(int32_t)v63, (struct _TYPEDEF_GUID *)v52, (struct _TYPEDEF_GUID *)0x20000, (int32_t)&v59, (struct _EVENT_DATA_DESCRIPTOR *)&v59);
                }
            }
        }
    }
    // 0x40164d
    ShellExecuteW(&v59, (int16_t *)&v59, (int16_t *)&v59, (int16_t *)&v59, (int16_t *)&v59, (int32_t)&v59);
    return function_401680((int32_t)&v59);
}

// Address range: 0x401680 - 0x401799
int32_t function_401680(int32_t a1) {
    int32_t v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int16_t * v5;
    int32_t v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int64_t * v10;
    int32_t v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int16_t *** v25;
    int16_t *** v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    // 0x401680
    int32_t result;
    int32_t v39;
    int32_t v40;
    if (v39 == v40) {
        // 0x401688
        return result;
    }
    // 0x401690
    int32_t v41;
    int32_t v42 = v41; // bp-4
    int32_t v43 = &v42; // 0x401692
    int32_t v44 = v43 - 804; // 0x401695
    int32_t v45 = result;
    int32_t v46 = v39;
    int32_t v47;
    int32_t v48 = v47;
    int32_t v49;
    int32_t v50 = v49;
    int32_t v51;
    int32_t v52 = v51;
    int32_t v53;
    int32_t v54 = v53;
    int32_t v55 = llvm_ctpop_i8((char)v44) % 2 == 0 ? 4 : 0; // 0x4016e8
    int32_t v56 = (v43 & 12) > 19 ? 16 : 0; // 0x4016e8
    int32_t v57 = v44 == 0 ? 64 : 0; // 0x4016e8
    bool v58;
    int32_t v59 = v58 ? 256 : 0; // 0x4016e8
    bool v60;
    int32_t v61 = v60 ? 512 : 0; // 0x4016e8
    bool v62;
    int32_t v63 = v62 ? 1024 : 0; // 0x4016e8
    bool v64;
    int32_t v65 = v64 ? 0x4000 : 0; // 0x4016e8
    int32_t v66 = (int32_t)(&v42 < (int32_t *)804) | v57 | v44 >> 31 & 128 | v56 | (803 - v43 & v43) >> 31 & 2048 | v55 | v59 | v61 | v63 | v65 | 2;
    int32_t v67 = 0x10001;
    int32_t v68 = a1;
    int32_t v69;
    int32_t v70 = &v69;
    int32_t v71 = v41;
    int32_t v72 = a1;
    int32_t v73 = -0x3ffffbf7;
    int32_t v74 = 1;
    int32_t v75 = 1;
    int32_t v76 = 2;
    SetUnhandledExceptionFilter(NULL);
    struct _EXCEPTION_POINTERS * ExceptionInfo;
    UnhandledExceptionFilter((struct _EXCEPTION_POINTERS *)&ExceptionInfo);
    int32_t * processHandle = GetCurrentProcess(); // 0x401788
    int32_t uExitCode;
    return TerminateProcess(processHandle, (int32_t)&uExitCode);
}

// Address range: 0x401799 - 0x40181f
int32_t function_401799(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int16_t *** v41;
    int16_t *** v42;
    int32_t v43;
    int32_t v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t lpPerformanceCount = 0; // bp-16
    int32_t v56;
    int32_t v57;
    if (v56 != 0) {
        if (v56 != -0x44bf19b2) {
            // 0x401812
            v57 = -1 - v56;
            int32_t result;
            return result;
        }
    }
    // 0x4017bd
    int32_t lpSystemTimeAsFileTime; // bp-24
    GetSystemTimeAsFileTime((struct _FILETIME *)&lpSystemTimeAsFileTime);
    int32_t v58;
    int32_t v59 = lpSystemTimeAsFileTime ^ v58; // 0x4017ca
    int32_t processId = GetCurrentProcessId(); // 0x4017d0
    int32_t threadId = GetCurrentThreadId(); // 0x4017d9
    int32_t v60 = GetTickCount(); // 0x4017e2
    int32_t v61; // bp-8
    v61 = threadId ^ processId ^ v59 ^ (int32_t)&v61 ^ v60;
    QueryPerformanceCounter((struct _LARGE_INTEGER *)&lpPerformanceCount);
    int32_t v62 = v61 ^ lpPerformanceCount; // 0x401806
    int32_t v63; // 0x40180c
    if (v62 == 0) {
        // 0x40180a
        v63 = -0x44bf19b2;
    } else {
        v63 = v62;
    }
    // 0x40180c
    v56 = v63;
    // 0x401812
    v57 = -1 - v63;
    return lpPerformanceCount;
}

// Address range: 0x401820 - 0x401886
int32_t function_401820(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int16_t *** v42;
    int16_t *** v43;
    int32_t v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52 = function_401ac5();
    __set_app_type(function_401c0e(2));
    int32_t v53 = -1;
    int32_t v54 = -1;
    int32_t v55;
    *__p__fmode() = v55;
    int32_t v56;
    *__p__commode() = v56;
    function_401c50();
    int32_t v57;
    if (v57 == 0) {
        // 0x401872
        __setusermatherr(0x401c50);
    }
    // 0x40187e
    function_401da5();
    return 0;
}

// Address range: 0x401890 - 0x4018c3
int32_t function_401890(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int32_t v43;
    int32_t v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    // 0x401890
    int32_t v51;
    int32_t v52 = v51;
    int32_t v53;
    int16_t *** v54;
    int16_t *** v55;
    int32_t v56;
    int32_t result = __wgetmainargs(&v53, (int16_t ***)&v54, (int16_t ***)&v55, v56, &v52); // 0x4018b4
    int32_t v57 = result;
    return result;
}

// Address range: 0x4018c3 - 0x401a94
int32_t function_4018c3(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int16_t *** v41;
    int16_t *** v42;
    int32_t v43;
    int32_t v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    // 0x4018c3
    int32_t dwMilliseconds;
    function_401dc0(0x401e60, 88, (int32_t)&dwMilliseconds);
    int32_t v51 = 0;
    int32_t v52;
    GetStartupInfoW((struct _STARTUPINFOW *)(v52 - 104));
    __readfsdword(24);
    int32_t v53 = v51;
    int32_t v54;
    int32_t v55 = v54; // 0x4018f547
    int32_t v56; // 0x4018e7
    v54 = v55 == 0 ? v56 : v55;
    if (v55 == 0) {
      lab_0x401915:;
    } else {
        while (true) {
            if (v55 == v56) {
                // break -> 0x401901
                break;
            }
            // 0x401908
            Sleep((int32_t)&dwMilliseconds);
            int32_t v57 = v54; // 0x4018f5
            v54 = v57 == 0 ? v56 : v57;
            if (v57 == 0) {
                goto lab_0x401915;
            }
            v55 = v57;
        }
        // 0x401901
        v53 = 1;
    }
    // 0x401918
    int32_t v58;
    int32_t v59 = v58; // 0x401918
    int32_t v60;
    int32_t result; // 0x401a8e
    if (v59 != 1) {
        // 0x40192a
        if (v59 != v51) {
            // 0x40195e
            v60 = 1;
        } else {
            // 0x401932
            v58 = 1;
            if (function_401a94((int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds) != 0) {
                // 0x401a8e
                result = function_401e05((int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds);
                return result;
            }
        }
    } else {
        // 0x401920
        _amsg_exit((int32_t)&dwMilliseconds);
    }
    // 0x401964
    if (v58 == 1) {
        // 0x40196c
        _initterm((void (**)())&dwMilliseconds, (void (**)())&dwMilliseconds);
        v58 = 2;
    }
    // 0x401987
    if (v53 == 0) {
        // 0x40198b
        v54 = 0;
    }
    // 0x401994
    int32_t v61;
    if (v61 != 0) {
        // 0x40199d
        if (function_401cb0((int32_t)&dwMilliseconds) != 0) {
            // 0x4019ac
            int32_t v62;
            *(int32_t *)v62 = v51;
            function_401e50();
        }
    }
    int32_t v63 = 0x3368; // ecx
    int32_t v64 = 32; // esi
    int32_t v65 = 32; // 0x4019d7
    int32_t v66; // 0x4019ef46
    while (true) {
        int32_t v67 = v63; // 0x4019d4
        uint16_t v68; // 0x4019d4
        int32_t v69; // 0x4019d1
        if (v68 <= (int16_t)v65) {
            if (v68 == 0) {
                // break -> 0x4019fa
                break;
            }
            // 0x4019e1
            if (v69 == 0) {
                v66 = v67;
                goto lab_0x4019ef_2;
            }
        }
        int32_t v70; // 0x401a3c
        if (v68 == 34) {
            // 0x401a30
            v69 = v69 == 0;
            v70 = v63;
        } else {
            v70 = v67;
        }
        // 0x401a3c
        v63 = v70 + 2;
        v65 = v64;
    }
    goto lab_0x4019fa;
  lab_0x4019fa:;
    // 0x4019fa
    unsigned char v71; // 0x4019fa
    if (v71 % 2 == 0) {
        // branch -> 0x401a09
    }
    int32_t v72 = function_401513();
    int32_t v73;
    if (v73 == 0) {
        // 0x401a24
        exit((int32_t)&dwMilliseconds);
        // UNREACHABLE
    }
    // 0x401a73
    if (v60 == 0) {
        // 0x401a7c
        _cexit();
    }
    // 0x401a8e
    result = function_401e05((int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds, (int32_t)&dwMilliseconds);
    return result;
  lab_0x4019ef_2:;
    // 0x4019ef
    uint16_t v74; // 0x4019f5
    if (v74 == 0) {
        goto lab_0x4019fa;
    } else {
        // 0x4019ef
        if (v74 > (int16_t)v64) {
            goto lab_0x4019fa;
        } else {
            v66 += 2;
            goto lab_0x4019ef_2;
        }
    }
}

// Address range: 0x401a94 - 0x401ac5
int32_t function_401a94(int32_t a1, uint32_t a2) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    int32_t v58 = a1; // esi
    if (a1 >= a2) {
        // 0x401ac2
        return 0;
    }
    int32_t v59 = 0; // 0x401aa5
    int32_t result; // 0x401ac47
    while (true) {
        if (v59 != 0) {
            result = v59;
            // break -> 0x401ac1
            break;
        }
        // 0x401aa9
        int32_t v60; // 0x401aa51
        int32_t v61; // 0x401ab9
        int32_t v62; // 0x401aa9
        if (v62 != 0) {
            // 0x401aaf
            v61 = v58;
            v60 = function_401e50();
        } else {
            v61 = a1;
            v60 = v59;
        }
        int32_t v63 = v61 + 4; // 0x401ab9
        v58 = v63;
        if (v63 >= a2) {
            result = v60;
            // break -> 0x401ac1
            break;
        }
        a1 = v63;
        v59 = v60;
    }
    // 0x401ac2
    return result;
}

// Address range: 0x401ac5 - 0x401b2b
int32_t function_401ac5(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401ac5
    int16_t v58; // 0x401aca
    int32_t v59; // 0x401ad9
    if (v58 != 0x5a4d || v59 != 0x4550) {
        // 0x401b28
        return 0;
    }
    // 0x401ae5
    int32_t v60;
    uint16_t v61; // 0x401ae5
    if (v61 == 267) {
        // 0x401b15
        uint32_t v62; // 0x401b15
        if (v62 < 15) {
            // 0x401b28
            return 0;
        }
        // 0x401b11
        return v60 != 0;
    }
    uint32_t v63; // 0x401b00
    if (v61 != 523 || v63 < 15) {
        // 0x401b28
        return 0;
    }
    // 0x401b11
    return v60 != 0;
}

// Address range: 0x401b30 - 0x401b3a
int32_t entry_point(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401b30
    function_401799();
    return function_4018c3();
}

// Address range: 0x401b42 - 0x401b83
int32_t function_401b42(int32_t a1) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    int32_t v58; // 0x401b4a
    int32_t v59; // 0x401b52
    if (v58 != -0x1f928c9d || v59 != 3) {
        // 0x401b7d
        return 0;
    }
    // 0x401b58
    int32_t v60; // 0x401b58
    if (v60 != 0x19930520) {
        if (v60 != 0x19930521) {
            if (v60 != 0x19930522) {
                if (v60 != 0x1994000) {
                    // 0x401b7d
                    return 0;
                }
            }
        }
    }
    // 0x401b77
    int32_t v61; // ebp
    _3f_terminate_40__40_YAXXZ(v61);
    // 0x401b7d
    return 0;
}

// Address range: 0x401b90 - 0x401b9e
int32_t (*function_401b90(int32_t (*lpTopLevelExceptionFilter)(struct _EXCEPTION_POINTERS *)))(struct _EXCEPTION_POINTERS *) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401b90
    SetUnhandledExceptionFilter(lpTopLevelExceptionFilter);
    return NULL;
}

// Address range: 0x401b9e - 0x401ba4
int32_t function_401b9e(int32_t xcptnum, int32_t * pxcptinfoptrs) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401b9e
    return _XcptFilter(xcptnum, pxcptinfoptrs);
}

// Address range: 0x401ba4 - 0x401c0e
int32_t function_401ba4(int32_t a1) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    // 0x401ba4
    int32_t v57;
    function_401dc0(0x401e80, 12, (int32_t)&v57);
    int32_t v58; // 0x401bb2
    int32_t result; // 0x401c06
    if (v58 == 0) {
        // 0x401c04
        result = function_401e05((int32_t)&v57, (int32_t)&v57, (int32_t)&v57, (int32_t)&v57, (int32_t)&v57);
        return result;
    }
    if (v58 == -1) {
        // 0x401c04
        result = function_401e05((int32_t)&v57, (int32_t)&v57, (int32_t)&v57, (int32_t)&v57, (int32_t)&v57);
        return result;
    }
    // 0x401bbe
    if (*(int16_t *)v58 == 0x5a4d) {
        // 0x401bcb
        uint32_t v59; // 0x401bcb
        if (v59 >= 0) {
            if (v59 < 0x10000000) {
                // branch -> 0x401bfd
            }
        }
    }
    // 0x401c04
    result = function_401e05((int32_t)&v57, (int32_t)&v57, (int32_t)&v57, (int32_t)&v57, (int32_t)&v57);
    return result;
}

// Address range: 0x401c0e - 0x401c44
int32_t function_401c0e(int32_t result) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    int32_t * v58 = GetModuleHandleW(NULL); // 0x401c15
    if (v58 == NULL || function_401ba4((int32_t)v58) == 0) {
        // 0x401c42
        return result;
    }
    // 0x401c29
    int16_t v59; // 0x401c29
    if (v59 == 2) {
        // 0x401c42
        return 2;
    }
    if (v59 == 3) {
        // 0x401c3a
        return 1;
    }
    // 0x401c42
    return result;
}

// Address range: 0x401c44 - 0x401c4a
void function_401c44(int32_t rterrnum) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401c44
    _amsg_exit(rterrnum);
}

// Address range: 0x401c50 - 0x401c53
int32_t function_401c50(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401c50
    return 0;
}

// Address range: 0x401c60 - 0x401ca5
int32_t function_401c60(int32_t a1, uint32_t a2) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401c60
    uint16_t v58; // 0x401c76
    if (v58 == 0) {
        // 0x401ca0
        return 0;
    }
    int32_t v59 = 0; // 0x401c96
    int32_t v60; // 0x401c6d
    uint16_t v61; // 0x401c72
    int32_t result = v60 + a1 + 24 + (int32_t)v61; // 0x401c97
    while (true) {
        // 0x401c86
        uint32_t v62; // 0x401c86
        if (v62 <= a2) {
            // 0x401c8d
            int32_t v63; // 0x401c8d
            if (v63 + v62 > a2) {
                return result;
            }
        }
        int32_t v64 = v59 + 1; // 0x401c96
        if (v64 >= (int32_t)v58) {
            // break -> 0x401c9e
            break;
        }
        v59 = v64;
        result += 40;
    }
    // 0x401ca0
    return 0;
}

// Address range: 0x401cb0 - 0x401d6c
int32_t function_401cb0(int32_t a1) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int16_t *** v42;
    int16_t *** v43;
    int32_t v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57 = __readfsdword(0); // bp-20
    int32_t v58;
    int32_t v59;
    int32_t v60 = (int32_t)&v58 ^ v59; // bp-44
    __writefsdword(0, (int32_t)&v57);
    int32_t v61;
    int32_t v62;
    int32_t v63;
    int32_t v64 = function_401d70(0x400000, v60, v62, v63, v61, &v60, v57, 0x401e20, v59 ^ 0x401ea0, 0, v58); // 0x401cf1
    if (v64 != 0) {
        // 0x401cfd
        if (function_401c60(0x400000, a1 - 0x400000) != 0) {
            // 0x401d17
            __writefsdword(0, v57);
            int32_t v65; // 0x401d17
            return v65 > -1;
        }
    }
    // 0x401d51
    __writefsdword(0, v57);
    return 0;
}

// Address range: 0x401d70 - 0x401da5
int32_t function_401d70(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t * a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401d70
    int16_t v58; // 0x401d7d
    int32_t v59; // 0x401d87
    int16_t v60; // 0x401d94
    if (v58 != 0x5a4d || v59 != 0x4550 || v60 != 267) {
        // 0x401da1
        return 0;
    }
    // 0x401d9a
    return 1;
}

// Address range: 0x401da5 - 0x401db8
int32_t function_401da5(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401da5
    return _controlfp(0x10000, 0x30000);
}

// Address range: 0x401db8 - 0x401dbe
void function_401db8(void (**First)(), void (**Last)()) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401db8
    _initterm(First, Last);
}

// Address range: 0x401dc0 - 0x401e05
int32_t function_401dc0(int32_t a1, int32_t a2, int32_t a3) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    int32_t v58 = __readfsdword(0); // bp-8
    int32_t result = &v58; // 0x401dc5
    __writefsdword(0, result);
    return result;
}

// Address range: 0x401e05 - 0x401e19
int32_t function_401e05(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401e05
    int32_t v58; // 0x401e05
    __writefsdword(0, v58);
    int32_t result;
    return result;
}

// Address range: 0x401e22 - 0x401e45
int32_t function_401e22(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401e22
    return _except_handler4_common();
}

// Address range: 0x401e50 - 0x401e53
int32_t function_401e50(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401e50
    int32_t result;
    return result;
}

// Address range: 0x401e53 - 0x401e59
int32_t function_401e53(void) {
    struct _EXCEPTION_POINTERS * v1;
    int32_t v2;
    int32_t v3;
    int32_t v4;
    int32_t v5;
    int16_t * v6;
    int32_t v7;
    int32_t v8;
    int32_t v9;
    int32_t v10;
    int64_t * v11;
    int32_t v12;
    int32_t v13;
    int32_t v14;
    int32_t v15;
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20;
    int32_t v21;
    int32_t v22;
    int32_t v23;
    int32_t v24;
    int32_t v25;
    int32_t v26;
    int32_t v27;
    int32_t v28;
    int32_t v29;
    int32_t v30;
    int32_t v31;
    int32_t v32;
    int32_t v33;
    int32_t v34;
    int32_t v35;
    int32_t v36;
    int32_t v37;
    int32_t v38;
    int32_t v39;
    int32_t v40;
    int32_t v41;
    int32_t v42;
    int16_t *** v43;
    int16_t *** v44;
    int32_t v45;
    int32_t v46;
    int32_t v47;
    int32_t v48;
    int32_t v49;
    int32_t v50;
    int32_t v51;
    int32_t v52;
    int32_t v53;
    int32_t v54;
    int32_t v55;
    int32_t v56;
    int32_t v57;
    // 0x401e53
    return _except_handler4_common();
}

// --------------- Dynamically Linked Functions ---------------

// int32_t _3f_terminate_40__40_YAXXZ(int32_t a1);
// int * __cdecl __p__commode(void);
// int * __cdecl __p__fmode(void);
// void __set_app_type(int at);
// void __setusermatherr(_HANDLE_MATH_ERROR pf);
// int __wgetmainargs(int * Argc, wchar_t *** Argv, wchar_t *** Env, int DoWildCard, _startupinfo * StartInfo);
// void _amsg_exit(int rterrnum);
// void __cdecl _cexit(void);
// unsigned int __cdecl _controlfp(_In_ unsigned int NewValue, _In_ unsigned int Mask);
// int _except_handler4_common(void);
// void __cdecl _initterm(_In_ _PVFV * First, _In_ _PVFV * Last);
// int _XcptFilter(unsigned long xcptnum, void * pxcptinfoptrs);
// ULONG EventRegister(_In_ LPCGUID ProviderId, _In_opt_ PENABLECALLBACK EnableCallback, _In_opt_ PVOID CallbackContext, _Out_ PREGHANDLE RegHandle);
// ULONG EventSetInformation(_In_ REGHANDLE RegHandle, _In_ EVENT_INFO_CLASS InformationClass, PVOID EventInformation, _In_ ULONG InformationLength);
// ULONG EventWriteTransfer(_In_ REGHANDLE RegHandle, _In_ PCEVENT_DESCRIPTOR EventDescriptor, _In_opt_ LPCGUID ActivityId, _In_opt_ LPCGUID RelatedActivityId, _In_ ULONG UserDataCount, PEVENT_DATA_DESCRIPTOR UserData);
// void exit(int status);
// HANDLE GetCurrentProcess(VOID);
// DWORD GetCurrentProcessId(VOID);
// DWORD GetCurrentThreadId(VOID);
// HMODULE GetModuleHandleW(_In_opt_ LPCWSTR lpModuleName);
// VOID GetStartupInfoW(_Out_ LPSTARTUPINFOW lpStartupInfo);
// VOID GetSystemTimeAsFileTime(_Out_ LPFILETIME lpSystemTimeAsFileTime);
// DWORD GetTickCount(VOID);
// BOOL QueryPerformanceCounter(_Out_ LARGE_INTEGER * lpPerformanceCount);
// LPTOP_LEVEL_EXCEPTION_FILTER SetUnhandledExceptionFilter(_In_opt_ LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// HINSTANCE ShellExecuteW(_In_opt_ HWND hwnd, _In_opt_ LPCWSTR lpOperation, _In_ LPCWSTR lpFile, _In_opt_ LPCWSTR lpParameters, _In_opt_ LPCWSTR lpDirectory, _In_ INT nShowCmd);
// VOID Sleep(_In_ DWORD dwMilliseconds);
// BOOL TerminateProcess(_In_ HANDLE hProcess, _In_ UINT uExitCode);
// LONG UnhandledExceptionFilter(_In_ struct _EXCEPTION_POINTERS * ExceptionInfo);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: vmprotect
// Detected functions: 29
// Decompilation date: 2019-04-10 17:30:39
